#!/usr/bin/env bash
# web-tools deploy — split-wrapper model.
#
# Runs as the invoking human (donjor or logworc), uses their forwarded SSH
# agent for GitHub auth. Only the PM2 ops at the end shell out to
# `sudo -Hu webtools` so the supervisor daemon stays under one canonical user
# regardless of who triggered the deploy.
#
# Invoked via /usr/local/bin/web-tools (the thin wrapper installed on test).
# Run from anywhere — script always cd's into /srv/web-tools.
#
# Externals are auto-discovered from scripts/externals/<slug>.toml. The
# directory is conventional (apps/external/<slug>). `bun install` triggers
# scripts/postinstall.sh which installs deps for every external.

set -euo pipefail
umask 002    # belt-and-braces: keep files group-writable even from non-interactive shells

# Non-interactive ssh skips ~/.bashrc, so bun isn't on PATH by default. Put it
# back so `web-tools deploy` works whether you ran it from a login shell or
# via `ssh test 'web-tools deploy'`.
export PATH="$HOME/.bun/bin:$PATH"

REPO=/srv/web-tools
cd "$REPO"

echo "▶ git pull (as $USER, using your forwarded SSH agent)"
git pull --ff-only
git submodule update --init --recursive

echo "▶ bun install (also runs scripts/postinstall.sh → installs every external)"
bun install

echo "▶ build each external (postinstall handled install)"
# Memory-constrained LXC: NODE_OPTIONS caps Node heap so swap absorbs spikes
# instead of the kernel killing the build. Externals with vite skip the
# upstream `tsc --noEmit && vite build` and run vite directly — type-checking
# is a CI concern, not a deploy concern.
shopt -s nullglob
for toml in "$REPO/scripts/externals/"*.toml; do
  slug=$(basename "$toml" .toml)
  dir="apps/external/$slug"
  [ -f "$REPO/$dir/package.json" ] || { echo "  · $dir — not present, skipped"; continue; }
  echo "  · $dir"
  if [ -x "$REPO/$dir/node_modules/.bin/vite" ]; then
    ( cd "$REPO/$dir" && NODE_OPTIONS="--max-old-space-size=384" ./node_modules/.bin/vite build )
  else
    ( cd "$REPO/$dir" && NODE_OPTIONS="--max-old-space-size=384" \
        bun run build || echo "    (no build script — skipped)" )
  fi
done
shopt -u nullglob

echo "▶ write preview-config overrides for externals served via Vite preview"
# Vite 6.3+ has a Host-header allowlist (CVE-2025-30208) — preview rejects
# requests for any hostname not in preview.allowedHosts. We patch a small
# override config next to each external's vite.config so the prod hostname
# is accepted. Generated, not committed.
write_vite_preview_config() {
  local dir="$1" port="$2"
  cat > "$REPO/$dir/vite.deploy.preview.config.ts" <<EOF
// Generated by web-tools deploy.sh — DO NOT EDIT.
// Adds preview.allowedHosts so Vite serves the prod Caddy hostname.
import { defineConfig } from "vite";
import base from "./vite.config";

export default defineConfig({
  ...(typeof base === "function" ? await base({ command: "serve", mode: "production" }) : base),
  preview: {
    host: "0.0.0.0",
    port: ${port},
    strictPort: true,
    allowedHosts: true,
  },
});
EOF
}
write_vite_preview_config "apps/external/r3f-examples" 3301

echo "▶ bun run build (host)"
bun run build

echo "▶ pm2 startOrReload (as webtools)"
sudo -Hu webtools pm2 startOrReload "$REPO/ecosystem.config.cjs"
sudo -Hu webtools pm2 save

echo "✓ deploy complete"
sudo -Hu webtools pm2 status
